name: build
on: push
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.x'
          channel: stable
      - name: Build apk 
        working-directory: front
        run: |
          flutter pub get
          flutter test
